### ISSUE TITLE
Adding a base directory specification feature to runners

### ISSUE THREAD

**Issue by devsepnine** [vbem/multi-runners#10]
Hi there,
Thanks to this, i conveniently configured github actions. 🙏🏻

I have a question regarding the runner directory. Is it possible to specify a custom directory for the runners instead of using the default /home directory?
Any information or guidance on this matter would be greatly appreciated.
TY

**Comment by vbem** [comment]
Hi,

Thank you for your praise.

Currently the runner will be installed under `$HOME/runner/` of each **runner-dedicated Linux user** to minimize the Linux permission issues. And the "Linux user to runner 1-1 mapping" was designed because we need to not only isolate different runners' building environment (such as caches under `~/.some-dir/`), but also to start the runner as an [user level `systemd` service](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/configuring-the-self-hosted-runner-application-as-a-service).

I'm not sure if you encountered some storage limit of the system-disk, could you please try mount the data-disk as `/home`?

**Comment by devsepnine** [comment]
I wanted to manage it in an external storage at first, but after using it for a few days, I think it's okay since it doesn't bother me.

**Comment by rrauenza** [comment]
I was going to ask same thing and also thank you for this tool.
 
In my use case, our standard machine deployment has all extra storage in /opt, so having a base directory of /opt would be ... "optimal" :)

so the ask would be to change 

```
../multi-runners/mr.bash:        && run::log sudo useradd -m -s /bin/bash -G 'runners,docker' "$user" >&2 || return $?
```

to 

```
../multi-runners/mr.bash:        && run::log sudo useradd -d "$base"/"$user" -m -s /bin/bash -G 'runners,docker' "$user" >&2 || return $?
```

Where `$base` defaults to `/home`, but could be overridden on the mr.bash command line.

**Comment by rrauenza** [comment]
I've made a PR
https://github.com/vbem/multi-runners/pull/15
