### ISSUE TITLE
Running out of space: Share same _work directory for all runners?

### ISSUE THREAD

**Issue by Akronae** [vbem/multi-runners#21]
Hi,

Thank you for your tool, it's really handy helping us manage ~30 runners.
One big issue I'm facing is that my 85GB SSD machines are quickly running out of storage.

This is mainly caused by the infamous `node_modules` folder being replicated for all runners (up to 8 on each machine).
It would be really helpful if those `_work` directories could be shared among runners.
In essence it could not only save space but also time I guess.  

Do you think it could be doable?  
I'd be happy to make a PR.

![image](https://github.com/user-attachments/assets/4a2db772-ba40-4f37-9356-6af7df33aa78)
![image](https://github.com/user-attachments/assets/bda773e3-5b25-4724-a823-320af20d2946)
![image](https://github.com/user-attachments/assets/826ad0ce-8a75-4299-a49d-cb57693843c1)

**Comment by vbem** [comment]
Hi Akronae,

I am very pleased to receive your feedback on usage.

Actually, the `_work` directory is the home directory of many workflow [contexts](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs), such as `${{ runner.temp }}`, `${{ runner.workspace }}`, `${{ github.workspace }}`, etc. Sharing it among multi runners on the same host may cause conflicts of different workflow runs.

However, if the `node_modules` folder is the largest duplication occupant, maybe you can simply create a [shared folder](https://www.tutorialspoint.com/how-to-create-a-shared-directory-for-all-users-in-linux) on the Linux host (e.g. `/home/SharedFolder`), and set the `NODE_PATH: /home/SharedFolder/.node_modules` environment variable in all related workflow files. Please note that as all runners created by this application were already in a shared Linux group `runners`, the `/home/SharedFolder` should also be owned by this group.

The disk usage may also increase because logs, workspace caches, runners updates, etc. You can also re-create the runners in *crontab* daily or weekly as a more complete housekeeping.

**Comment by Akronae** [comment]
Ok, thanks for your help, I chose the recreate all runners periodically as this will also fix the issue where half the runners disconnect and go offline after a month or so.

This seems to work fine:
```bash
#!/bin/bash
for i in {0..7}
do
  bash multi-runners/mr.bash del --user runner-$i
  bash multi-runners/mr.bash add --org <my org>
done
```

Cheers 😄
