### ISSUE TITLE
Can I override the default name given to the runners?

### ISSUE THREAD

**Issue by ax-jrobb** [vbem/multi-runners#3]
This tool is super useful; thank you!!

I set up a handful of runners on an EC2 instance, and their names on `https://github.com/MY_ORG/MY_REPO/actions/runners?tab=self-hosted` are all something like `runner-2@ip-10-1-2-3.us-west-2.compute.internal`. 

Is there a way to override the name? If not, please consider this a feature request. :)

**Comment by vbem** [comment]
Hi @ax-jrobb ,

I am glad to receive your feedback.

Yes, you can change the runner name indirectly. Actually, this app set self-hosted **runners' name** as:

```bash
${incremental_linux_user_name}@${HOSTNAME}
```

This is because user may **create many runners on many hosts for a single repo or group** and this naming convention can help when distinguishing and debugging.

For the `${HOSTNAME}` part, it's the linux environment variable representing your host-machine (e.g. an *EC2* instance) hostname, which can be changed via `hostnamectl` or [other method depending on your Linux OS distribution](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html). After you changed it, remember to re-login the shell to makes the renewed  `${HOSTNAME}` environment variable available to this application.

For the `${incremental_linux_user_name}` part, it consists of two parts - `${MR_USER_PREFIX}${incremental_counting_number}`. The `${MR_USER_PREFIX}` is an environment variable you can define, and defaults to `runner-` if unset. For example you can define it in this application's `.env` file:

```bash
# multi-runners/.env file
MR_USER_PREFIX='myagent_'
```

Then your created runner' names will be:

```bash
myagent_0@hostname-a
myagent_1@hostname-a
myagent_2@hostname-a
myagent_0@hostname-b
myagent_1@hostname-b
....
```

Hope these can help you create manageable runners. 🙂

**Comment by ax-jrobb** [comment]
Great, thanks!
